-- MySQL Script generated by MySQL Workbench
-- Thu 16 Feb 2017 11:38:42 AM VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coagronorte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coagronorte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coagronorte` DEFAULT CHARACTER SET latin1 ;
USE `coagronorte` ;

-- -----------------------------------------------------
-- Table `coagronorte`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`actividades` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'contenido ',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Dominio para guardar las diferentes actividades que pueden realizarse';


-- -----------------------------------------------------
-- Table `coagronorte`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`departamentos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del departamento',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Dominio con información de departamentos';


-- -----------------------------------------------------
-- Table `coagronorte`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`municipios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del municipio',
  `codigo_departamento` INT(11) NOT NULL COMMENT 'clave foranea con tabla departamento',
  PRIMARY KEY (`codigo`),
  INDEX `municipios_fk0` (`codigo_departamento` ASC),
  CONSTRAINT `municipios_fk0`
    FOREIGN KEY (`codigo_departamento`)
    REFERENCES `coagronorte`.`departamentos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra con la información de los municipios';


-- -----------------------------------------------------
-- Table `coagronorte`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`ciudades` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre ciudad',
  `codigo_municipio` INT(11) NOT NULL COMMENT 'clave foranea con tabla municipio',
  PRIMARY KEY (`codigo`),
  INDEX `ciudades_fk0` (`codigo_municipio` ASC),
  CONSTRAINT `ciudades_fk0`
    FOREIGN KEY (`codigo_municipio`)
    REFERENCES `coagronorte`.`municipios` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Dominio de ciudades';


-- -----------------------------------------------------
-- Table `coagronorte`.`implementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`implementos` (
  `cod` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del iimplemento',
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla maestra de implementos';


-- -----------------------------------------------------
-- Table `coagronorte`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`tipo_usuarios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del tipo de usuario',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra para indicar tipo de usuarios: agricultor, agronomo...';


-- -----------------------------------------------------
-- Table `coagronorte`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`usuarios` (
  `cedula` VARCHAR(50) NOT NULL COMMENT 'identificador de la tabla',
  `nombre_usuario` VARCHAR(50) NOT NULL COMMENT 'nombre',
  `password` BLOB NOT NULL COMMENT 'credencial de acceso',
  `correo_electronico` VARCHAR(50) NOT NULL COMMENT 'correo electronico',
  `telefono` VARCHAR(50) NOT NULL COMMENT 'telefono',
  `fecha_inscripcion` DATETIME NULL DEFAULT NULL COMMENT 'fecha de inscripcion del agricultor',
  `codigo_tipo_usuario` INT(11) NOT NULL COMMENT 'clave foranea que indica que tipo de usuario es agricultor, agronomo ...',
  PRIMARY KEY (`cedula`),
  INDEX `usuarios_fk0` (`codigo_tipo_usuario` ASC),
  CONSTRAINT `usuarios_fk0`
    FOREIGN KEY (`codigo_tipo_usuario`)
    REFERENCES `coagronorte`.`tipo_usuarios` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'almacena la informacion de los usuarios de la aplicacion';


-- -----------------------------------------------------
-- Table `coagronorte`.`detalle_implementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`detalle_implementos` (
  `codigo_implementos` INT(11) NOT NULL COMMENT 'clave foranea con tabla implementos',
  `cedula_usuarios` VARCHAR(50) NOT NULL COMMENT 'clave foranea con tabla usuarios',
  `cantidad` INT(11) NOT NULL COMMENT 'cantidad de implementos que posee',
  `codigo` INT(11) NOT NULL COMMENT 'identificador de la tabla',
  PRIMARY KEY (`codigo`),
  INDEX `detalle_implementos_fk0` (`codigo_implementos` ASC),
  INDEX `detalle_implementos_fk1` (`cedula_usuarios` ASC),
  CONSTRAINT `detalle_implementos_fk0`
    FOREIGN KEY (`codigo_implementos`)
    REFERENCES `coagronorte`.`implementos` (`cod`),
  CONSTRAINT `detalle_implementos_fk1`
    FOREIGN KEY (`cedula_usuarios`)
    REFERENCES `coagronorte`.`usuarios` (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla asociativa con la información de los implemento con ue cuenta el agricultor';


-- -----------------------------------------------------
-- Table `coagronorte`.`plantillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`plantillas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `codigo_actividad` INT(11) NOT NULL COMMENT 'clave foranea con tabla actividad',
  `ciclo_dias_conteo` INT(11) NOT NULL COMMENT 'cuantos dias debe contar para el desarrollo de la actividad',
  `dias_alerta` INT(11) NOT NULL COMMENT 'con cuantos dias de alerta deben emitirse las notificaciones',
  PRIMARY KEY (`codigo`),
  INDEX `plantillas_fk0` (`codigo_actividad` ASC),
  CONSTRAINT `plantillas_fk0`
    FOREIGN KEY (`codigo_actividad`)
    REFERENCES `coagronorte`.`actividades` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'permite almacenar y configurar diferentes actividades a desarrollar por los usuarios';


-- -----------------------------------------------------
-- Table `coagronorte`.`detalle_plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`detalle_plantilla` (
  `codigo_plantilla` INT(11) NOT NULL COMMENT 'clave foranea con tabla plantilla',
  `cedula_usuario` VARCHAR(50) NOT NULL COMMENT 'clave foranea con tabla usuarios',
  `cumplimiento` BINARY(1) NOT NULL COMMENT 'variable booleana que denota el cumplimiento o no de la actividad',
  `fecha_inicio` DATETIME NOT NULL COMMENT 'fecha de inicio asignada al usuario para el cumplimiento de la actividad',
  PRIMARY KEY (`codigo_plantilla`, `cedula_usuario`),
  INDEX `detalle_plantilla_fk1` (`cedula_usuario` ASC),
  CONSTRAINT `detalle_plantilla_fk0`
    FOREIGN KEY (`codigo_plantilla`)
    REFERENCES `coagronorte`.`plantillas` (`codigo`),
  CONSTRAINT `detalle_plantilla_fk1`
    FOREIGN KEY (`cedula_usuario`)
    REFERENCES `coagronorte`.`usuarios` (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla asociativa entre la plantilla de actividades que debe cubrir un usuario determinado';


-- -----------------------------------------------------
-- Table `coagronorte`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`zonas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre de la zona',
  `codigo_ciudad` INT(11) NOT NULL COMMENT 'clave foranea con la tabla ciudad ',
  PRIMARY KEY (`codigo`),
  INDEX `zonas_fk0` (`codigo_ciudad` ASC),
  CONSTRAINT `zonas_fk0`
    FOREIGN KEY (`codigo_ciudad`)
    REFERENCES `coagronorte`.`ciudades` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla para almacenar las zonas ';


-- -----------------------------------------------------
-- Table `coagronorte`.`tipo_riegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`tipo_riegos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del tipo de riego',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra para indicar tipos de riegos';


-- -----------------------------------------------------
-- Table `coagronorte`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`lotes` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de tabla',
  `vereda` VARCHAR(50) NOT NULL COMMENT 'vereda de ubicacion',
  `codigo_zona` INT(11) NOT NULL COMMENT 'clave fornea con tabla zona. indica la zona  a la que pertenece',
  `area` DECIMAL(10,0) NOT NULL COMMENT 'metros cuadrados que posee el lote',
  `propietario` VARCHAR(50) NOT NULL COMMENT 'clave foranea tabla usuarios para saber de quue agricultor es el lote',
  `tenencia` ENUM('propio', 'arriendo', 'vencimiento') NOT NULL COMMENT 'indicador: propio,arriendo, vencimiento',
  `analisis_suelo` BINARY(1) NOT NULL COMMENT '1:Si, 0:No',
  `fecha_analisis_suelo` DATETIME NULL DEFAULT NULL COMMENT 'cuando se realizo el analisis de suelo',
  `PINSAT` BINARY(1) NOT NULL COMMENT '1:Si, 0:No ',
  `planos` BINARY(1) NOT NULL COMMENT '1:Si, 0:No',
  `archivo_planos` VARCHAR(50) NOT NULL COMMENT 'direccion archivo de planos',
  `venta` BINARY(1) NOT NULL COMMENT 'solo inscrito para venta 1:Si, 0:No',
  `asistencia_tecnica` BINARY(1) NOT NULL COMMENT 'servicio de asistencia tecnica de coagronorte 1:Si, 0:No',
  `codigo_riego` INT(11) NOT NULL COMMENT 'clave foranea tabla riego',
  `longitud` INT(11) NOT NULL COMMENT 'ubicacion',
  `latitud` INT(11) NOT NULL COMMENT 'ubicacion',
  PRIMARY KEY (`codigo`),
  INDEX `lotes_fk0` (`codigo_zona` ASC),
  INDEX `lotes_fk1` (`propietario` ASC),
  INDEX `lotes_fk2` (`codigo_riego` ASC),
  CONSTRAINT `lotes_fk0`
    FOREIGN KEY (`codigo_zona`)
    REFERENCES `coagronorte`.`zonas` (`codigo`),
  CONSTRAINT `lotes_fk1`
    FOREIGN KEY (`propietario`)
    REFERENCES `coagronorte`.`usuarios` (`cedula`),
  CONSTRAINT `lotes_fk2`
    FOREIGN KEY (`codigo_riego`)
    REFERENCES `coagronorte`.`tipo_riegos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'información de los lotes que maneja el agricultor';


-- -----------------------------------------------------
-- Table `coagronorte`.`tipo_semilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`tipo_semilla` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del tipo de semilla ',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra para indicar el tipo de semilla sembrada';


-- -----------------------------------------------------
-- Table `coagronorte`.`variedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`variedad` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre de la variedad',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra que almacena informacion acerca de la variedad sembrada';


-- -----------------------------------------------------
-- Table `coagronorte`.`tipo_siembra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`tipo_siembra` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre del tipo de semilla',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra que indica el tipo de semilla';


-- -----------------------------------------------------
-- Table `coagronorte`.`siembras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`siembras` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `fecha_siembra` DATETIME NOT NULL COMMENT 'fecha en la que se efectuo la siembra',
  `fecha_siembra_estimada` DATETIME NOT NULL COMMENT 'fecha en la que se estimo se debia sembrar',
  `fecha_estimada_corta` DATETIME NOT NULL COMMENT 'fecha en la que se estima que se haga el corte',
  `fecha_real_corta` DATETIME NOT NULL COMMENT 'fecha en la que se realizo el corte',
  `codigo_lote` INT(11) NOT NULL COMMENT 'clave foranea tabla lote indica el lote en el que se esta desarrollando la siembra',
  `dias_germinado` INT(11) NOT NULL COMMENT 'numero de dias para la germinacion',
  `hectareas` DECIMAL(10,0) NOT NULL COMMENT 'numero de hectareas',
  `punto_referencia` VARCHAR(50) NOT NULL COMMENT 'punto de referencia de la siembra',
  `sistema_preparacion` VARCHAR(50) NOT NULL COMMENT 'sistema de preparacion utilizado',
  `codigo_tipo_semilla` INT(11) NOT NULL COMMENT 'clave foranea tabla tipo_semilla',
  `codigo_variedad` INT(11) NOT NULL COMMENT 'clave foranea tabla variedad',
  `codigo_tipo_siembra` INT(11) NOT NULL COMMENT 'clave foranea tabla tipo de siembra',
  `arroz_rojo` ENUM('alto', 'medio', 'bajo') NULL DEFAULT NULL COMMENT 'para el informe de finalizacion. alto, medio bajo',
  `semilla_objetable` BINARY(1) NULL DEFAULT NULL COMMENT '1: Si 0:No',
  `rendimiento_ha` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'rendimiento en hectareas sembradas',
  `observaciones` TEXT NULL DEFAULT NULL COMMENT 'observaciones adicionales',
  PRIMARY KEY (`codigo`),
  INDEX `siembras_fk0` (`codigo_lote` ASC),
  INDEX `siembras_fk1` (`codigo_tipo_semilla` ASC),
  INDEX `siembras_fk2` (`codigo_variedad` ASC),
  INDEX `siembras_fk3` (`codigo_tipo_siembra` ASC),
  CONSTRAINT `siembras_fk0`
    FOREIGN KEY (`codigo_lote`)
    REFERENCES `coagronorte`.`lotes` (`codigo`),
  CONSTRAINT `siembras_fk1`
    FOREIGN KEY (`codigo_tipo_semilla`)
    REFERENCES `coagronorte`.`tipo_semilla` (`codigo`),
  CONSTRAINT `siembras_fk2`
    FOREIGN KEY (`codigo_variedad`)
    REFERENCES `coagronorte`.`variedad` (`codigo`),
  CONSTRAINT `siembras_fk3`
    FOREIGN KEY (`codigo_tipo_siembra`)
    REFERENCES `coagronorte`.`tipo_siembra` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'informacion sobre la siembra desarrollada';


-- -----------------------------------------------------
-- Table `coagronorte`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`visitas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'codigo de la visita',
  `codigo_siembra` INT(11) NOT NULL COMMENT 'clave foranea con codigo de la siembra que se visita',
  `fecha` DATETIME NOT NULL COMMENT 'fecha en la que se realiza la visita',
  `presencia_agricultor` BINARY(1) NOT NULL COMMENT 'hubo presencia del agricultor en la visita 1:Si 0:No',
  `registro_ausencia` TEXT NULL DEFAULT NULL COMMENT 'justificacion de la ausencia del agricultor',
  `validado` BINARY(1) NOT NULL COMMENT 'indica si el agricultor ya valido el informe de la visita 1:Si 0:No',
  `valoracion` INT(11) NOT NULL COMMENT 'valoracion otorgada por agricultor al agronomo durante la visita 1 - 5',
  `opinion` TEXT NOT NULL COMMENT 'opinion emitida por agricultor a la visita',
  `agronomo` VARCHAR(50) NOT NULL COMMENT 'clave foranea con tabla usuarios para identificar que agronomo realizo la visita',
  `archivo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ruta del archivo de voz utilizado para registrar la ausencia del agricultor',
  PRIMARY KEY (`codigo`, `codigo_siembra`),
  INDEX `visitas_fk0` (`codigo_siembra` ASC),
  INDEX `visitas_fk1` (`agronomo` ASC),
  CONSTRAINT `visitas_fk0`
    FOREIGN KEY (`codigo_siembra`)
    REFERENCES `coagronorte`.`siembras` (`codigo`),
  CONSTRAINT `visitas_fk1`
    FOREIGN KEY (`agronomo`)
    REFERENCES `coagronorte`.`usuarios` (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla que almacena las visitas realizadas a una siembra';


-- -----------------------------------------------------
-- Table `coagronorte`.`estado_siembras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`estado_siembras` (
  `numero` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `archivo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'almacena la ruta del archivo de voz o imagen',
  `descripcion` TEXT NOT NULL COMMENT 'texto de la nota de voz',
  `fecha` DATETIME NOT NULL COMMENT 'fecha y hora de la nota de voz o foto',
  `duracion` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'duracion de la nota de voz',
  `tamano` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'tamano de la imagen adjuntada',
  `tipo` ENUM('imagen', 'voz') NOT NULL COMMENT 'imagen, voz ',
  `codigo_visitas` INT(11) NOT NULL COMMENT 'clave foranea con tabla visitas',
  PRIMARY KEY (`numero`),
  INDEX `estado_siembras_fk0` (`codigo_visitas` ASC),
  CONSTRAINT `estado_siembras_fk0`
    FOREIGN KEY (`codigo_visitas`)
    REFERENCES `coagronorte`.`visitas` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Almacena el estado de una siembra determinada cuando se realiza una visita. Mecanismo para almacenar fotos, texto y notas de voz';


-- -----------------------------------------------------
-- Table `coagronorte`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coagronorte`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`productos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `nombre` VARCHAR(50) NOT NULL COMMENT 'nombre descripcion del producto',
  `codigo_unidad` INT(11) NOT NULL COMMENT 'clave fornaea con la tabla unidad para conocer la unidad en la que se expresa el producto',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra que almacena la información de los productos que pueden suministrarse y/o recomendarse';


-- -----------------------------------------------------
-- Table `coagronorte`.`producto_recomendaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`producto_recomendaciones` (
  `codigo_producto` INT(11) NOT NULL COMMENT 'clave foranea tabla producto',
  `codigo_visita` INT(11) NOT NULL COMMENT 'clave foranea tabla visita',
  `cantidad` DECIMAL(10,0) NOT NULL COMMENT 'cantidad a ser suminastrada',
  `dosis` DECIMAL(10,0) NOT NULL COMMENT 'dosis que debe suministrase',
  `recomendaciones` TEXT NOT NULL COMMENT 'texto con las recomendaciones para la administracion del producto',
  `aplicacion` BINARY(1) NOT NULL COMMENT 'se administro?: 1: Si, 0:No',
  `observaciones` TEXT NOT NULL COMMENT 'observaciones adicionales',
  `archivo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ruta del archivo de voz realizado para emitir las recomendaciones',
  PRIMARY KEY (`codigo_producto`, `codigo_visita`),
  INDEX `producto_recomendaciones_fk1` (`codigo_visita` ASC),
  CONSTRAINT `producto_recomendaciones_fk0`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `coagronorte`.`productos` (`codigo`),
  CONSTRAINT `producto_recomendaciones_fk1`
    FOREIGN KEY (`codigo_visita`)
    REFERENCES `coagronorte`.`visitas` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla asociativa que almacena la información acerca de los productos recomendados y en que visita se recomendaron. Cuando son suministros para comenzar a sembrar el codigo de la visita será el 1';


-- -----------------------------------------------------
-- Table `coagronorte`.`recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`recorridos` (
  `punto` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'consecutivo de puntos almacenados',
  `latitud` DECIMAL(10,0) NOT NULL COMMENT 'ubicacion',
  `longitud` DECIMAL(10,0) NOT NULL COMMENT 'ubicacion',
  `codigo_visita` INT(11) NOT NULL COMMENT 'clave foranea para identificar en que visita se guardo el punto estudiado',
  PRIMARY KEY (`punto`, `codigo_visita`),
  INDEX `recorridos_fk0` (`codigo_visita` ASC),
  CONSTRAINT `recorridos_fk0`
    FOREIGN KEY (`codigo_visita`)
    REFERENCES `coagronorte`.`visitas` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'almacena el recorrido realizado por el usuario al realizarse la visita';


-- -----------------------------------------------------
-- Table `coagronorte`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coagronorte`.`unidades` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'nombre de la unidad',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla maestra para guardar informacion de las unidades en las que pueden presentarse los productos';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
